- removed empty key section, which is causing yaml errors:
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.elastic_search.environment contains an invalid type, it should be an object, or
an array
(pygeoapi)